// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: master.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterControl_ReportStatus_FullMethodName        = "/proto.MasterControl/ReportStatus"
	MasterControl_GetConfig_FullMethodName           = "/proto.MasterControl/GetConfig"
	MasterControl_GetCommand_FullMethodName          = "/proto.MasterControl/GetCommand"
	MasterControl_ManageContainer_FullMethodName     = "/proto.MasterControl/ManageContainer"
	MasterControl_ReportCommandResult_FullMethodName = "/proto.MasterControl/ReportCommandResult"
)

// MasterControlClient is the client API for MasterControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// บริการหลักที่ Master จะเปิดให้ Worker เรียกใช้
type MasterControlClient interface {
	// Worker ส่งข้อมูลรายงานตัว (Heartbeat) - Unary RPC
	ReportStatus(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (*Ack, error)
	// Worker ร้องขอ Configuration ล่าสุด - Unary RPC
	GetConfig(ctx context.Context, in *NodeIdentity, opts ...grpc.CallOption) (*ConfigResponse, error)
	// Worker คอยฟังคำสั่งจาก Master - Server Streaming RPC
	GetCommand(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error)
	ManageContainer(ctx context.Context, in *ContainerAction, opts ...grpc.CallOption) (*Ack, error)
	// 🤖 เพิ่ม RPC ให้ Worker ส่งผลลัพธ์คำสั่งเชลล์กลับมา
	ReportCommandResult(ctx context.Context, in *CommandResult, opts ...grpc.CallOption) (*Ack, error)
}

type masterControlClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterControlClient(cc grpc.ClientConnInterface) MasterControlClient {
	return &masterControlClient{cc}
}

func (c *masterControlClient) ReportStatus(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MasterControl_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControlClient) GetConfig(ctx context.Context, in *NodeIdentity, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, MasterControl_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControlClient) GetCommand(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterControl_ServiceDesc.Streams[0], MasterControl_GetCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeStatus, Command]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterControl_GetCommandClient = grpc.ServerStreamingClient[Command]

func (c *masterControlClient) ManageContainer(ctx context.Context, in *ContainerAction, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MasterControl_ManageContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterControlClient) ReportCommandResult(ctx context.Context, in *CommandResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, MasterControl_ReportCommandResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterControlServer is the server API for MasterControl service.
// All implementations must embed UnimplementedMasterControlServer
// for forward compatibility.
//
// บริการหลักที่ Master จะเปิดให้ Worker เรียกใช้
type MasterControlServer interface {
	// Worker ส่งข้อมูลรายงานตัว (Heartbeat) - Unary RPC
	ReportStatus(context.Context, *NodeStatus) (*Ack, error)
	// Worker ร้องขอ Configuration ล่าสุด - Unary RPC
	GetConfig(context.Context, *NodeIdentity) (*ConfigResponse, error)
	// Worker คอยฟังคำสั่งจาก Master - Server Streaming RPC
	GetCommand(*NodeStatus, grpc.ServerStreamingServer[Command]) error
	ManageContainer(context.Context, *ContainerAction) (*Ack, error)
	// 🤖 เพิ่ม RPC ให้ Worker ส่งผลลัพธ์คำสั่งเชลล์กลับมา
	ReportCommandResult(context.Context, *CommandResult) (*Ack, error)
	mustEmbedUnimplementedMasterControlServer()
}

// UnimplementedMasterControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterControlServer struct{}

func (UnimplementedMasterControlServer) ReportStatus(context.Context, *NodeStatus) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedMasterControlServer) GetConfig(context.Context, *NodeIdentity) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedMasterControlServer) GetCommand(*NodeStatus, grpc.ServerStreamingServer[Command]) error {
	return status.Error(codes.Unimplemented, "method GetCommand not implemented")
}
func (UnimplementedMasterControlServer) ManageContainer(context.Context, *ContainerAction) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ManageContainer not implemented")
}
func (UnimplementedMasterControlServer) ReportCommandResult(context.Context, *CommandResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCommandResult not implemented")
}
func (UnimplementedMasterControlServer) mustEmbedUnimplementedMasterControlServer() {}
func (UnimplementedMasterControlServer) testEmbeddedByValue()                       {}

// UnsafeMasterControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterControlServer will
// result in compilation errors.
type UnsafeMasterControlServer interface {
	mustEmbedUnimplementedMasterControlServer()
}

func RegisterMasterControlServer(s grpc.ServiceRegistrar, srv MasterControlServer) {
	// If the following call panics, it indicates UnimplementedMasterControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterControl_ServiceDesc, srv)
}

func _MasterControl_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControlServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterControl_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControlServer).ReportStatus(ctx, req.(*NodeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterControl_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControlServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterControl_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControlServer).GetConfig(ctx, req.(*NodeIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterControl_GetCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeStatus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MasterControlServer).GetCommand(m, &grpc.GenericServerStream[NodeStatus, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterControl_GetCommandServer = grpc.ServerStreamingServer[Command]

func _MasterControl_ManageContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControlServer).ManageContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterControl_ManageContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControlServer).ManageContainer(ctx, req.(*ContainerAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterControl_ReportCommandResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterControlServer).ReportCommandResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterControl_ReportCommandResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterControlServer).ReportCommandResult(ctx, req.(*CommandResult))
	}
	return interceptor(ctx, in, info, handler)
}

// MasterControl_ServiceDesc is the grpc.ServiceDesc for MasterControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MasterControl",
	HandlerType: (*MasterControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _MasterControl_ReportStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _MasterControl_GetConfig_Handler,
		},
		{
			MethodName: "ManageContainer",
			Handler:    _MasterControl_ManageContainer_Handler,
		},
		{
			MethodName: "ReportCommandResult",
			Handler:    _MasterControl_ReportCommandResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCommand",
			Handler:       _MasterControl_GetCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "master.proto",
}
