// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/master.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ข้อความข้อมูลสถานะ
type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	VesselType    string                 `protobuf:"bytes,5,opt,name=vessel_type,json=vesselType,proto3" json:"vessel_type,omitempty"`
	IpAddress     string                 `protobuf:"bytes,6,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	OsInfo        string                 `protobuf:"bytes,7,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	SystemSpec    string                 `protobuf:"bytes,8,opt,name=system_spec,json=systemSpec,proto3" json:"system_spec,omitempty"`
	Tools         []string               `protobuf:"bytes,9,rep,name=tools,proto3" json:"tools,omitempty"`
	Role          string                 `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	Department    string                 `protobuf:"bytes,11,opt,name=department,proto3" json:"department,omitempty"`
	OrgId         string                 `protobuf:"bytes,12,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStatus) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *NodeStatus) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *NodeStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeStatus) GetVesselType() string {
	if x != nil {
		return x.VesselType
	}
	return ""
}

func (x *NodeStatus) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *NodeStatus) GetOsInfo() string {
	if x != nil {
		return x.OsInfo
	}
	return ""
}

func (x *NodeStatus) GetSystemSpec() string {
	if x != nil {
		return x.SystemSpec
	}
	return ""
}

func (x *NodeStatus) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *NodeStatus) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *NodeStatus) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *NodeStatus) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

// ข้อความการตอบรับ
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainerAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // เช่น "restart", "pull"
	ContainerName string                 `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerAction) Reset() {
	*x = ContainerAction{}
	mi := &file_proto_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerAction) ProtoMessage() {}

func (x *ContainerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerAction.ProtoReflect.Descriptor instead.
func (*ContainerAction) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerAction) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContainerAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ContainerAction) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

// ข้อความระบุตัวตนของ Worker
type NodeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SecretKey     string                 `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_proto_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{3}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetSecretKey() string {
	if x != nil {
		return x.SecretKey
	}
	return ""
}

// ข้อความ Configuration ที่ส่งกลับไปให้ Worker
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ProxyRules    string                 `protobuf:"bytes,2,opt,name=proxy_rules,json=proxyRules,proto3" json:"proxy_rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_proto_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ConfigResponse) GetProxyRules() string {
	if x != nil {
		return x.ProxyRules
	}
	return ""
}

// ข้อความคำสั่งที่จะส่งให้ Worker
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // รหัสอ้างอิงของงานที่สั่ง
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                            // ประเภทงาน เช่น "shell", "restart"
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // เนื้อหางาน เช่น `ls -al` หรือ `ps aux`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// 🤖 ข้อความส่งกลับจาก Worker หลังทำคำสั่งสำเร็จ/ล้มเหลว
type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"` // ผลลัพธ์ stdout หรือ stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_master_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

var File_proto_master_proto protoreflect.FileDescriptor

const file_proto_master_proto_rawDesc = "" +
	"\n" +
	"\x12proto/master.proto\x12\x05proto\"\xd2\x02\n" +
	"\n" +
	"NodeStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vvessel_type\x18\x05 \x01(\tR\n" +
	"vesselType\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x06 \x01(\tR\tipAddress\x12\x17\n" +
	"\aos_info\x18\a \x01(\tR\x06osInfo\x12\x1f\n" +
	"\vsystem_spec\x18\b \x01(\tR\n" +
	"systemSpec\x12\x14\n" +
	"\x05tools\x18\t \x03(\tR\x05tools\x12\x12\n" +
	"\x04role\x18\n" +
	" \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"department\x18\v \x01(\tR\n" +
	"department\x12\x15\n" +
	"\x06org_id\x18\f \x01(\tR\x05orgId\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"i\n" +
	"\x0fContainerAction\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"F\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tR\tsecretKey\"J\n" +
	"\x0eConfigResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vproxy_rules\x18\x02 \x01(\tR\n" +
	"proxyRules\"V\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"y\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\tR\x06output2\xa2\x02\n" +
	"\rMasterControl\x12/\n" +
	"\fReportStatus\x12\x11.proto.NodeStatus\x1a\n" +
	".proto.Ack\"\x00\x129\n" +
	"\tGetConfig\x12\x13.proto.NodeIdentity\x1a\x15.proto.ConfigResponse\"\x00\x123\n" +
	"\n" +
	"GetCommand\x12\x11.proto.NodeStatus\x1a\x0e.proto.Command\"\x000\x01\x125\n" +
	"\x0fManageContainer\x12\x16.proto.ContainerAction\x1a\n" +
	".proto.Ack\x129\n" +
	"\x13ReportCommandResult\x12\x14.proto.CommandResult\x1a\n" +
	".proto.Ack\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_master_proto_rawDescOnce sync.Once
	file_proto_master_proto_rawDescData []byte
)

func file_proto_master_proto_rawDescGZIP() []byte {
	file_proto_master_proto_rawDescOnce.Do(func() {
		file_proto_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)))
	})
	return file_proto_master_proto_rawDescData
}

var file_proto_master_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_master_proto_goTypes = []any{
	(*NodeStatus)(nil),      // 0: proto.NodeStatus
	(*Ack)(nil),             // 1: proto.Ack
	(*ContainerAction)(nil), // 2: proto.ContainerAction
	(*NodeIdentity)(nil),    // 3: proto.NodeIdentity
	(*ConfigResponse)(nil),  // 4: proto.ConfigResponse
	(*Command)(nil),         // 5: proto.Command
	(*CommandResult)(nil),   // 6: proto.CommandResult
}
var file_proto_master_proto_depIdxs = []int32{
	0, // 0: proto.MasterControl.ReportStatus:input_type -> proto.NodeStatus
	3, // 1: proto.MasterControl.GetConfig:input_type -> proto.NodeIdentity
	0, // 2: proto.MasterControl.GetCommand:input_type -> proto.NodeStatus
	2, // 3: proto.MasterControl.ManageContainer:input_type -> proto.ContainerAction
	6, // 4: proto.MasterControl.ReportCommandResult:input_type -> proto.CommandResult
	1, // 5: proto.MasterControl.ReportStatus:output_type -> proto.Ack
	4, // 6: proto.MasterControl.GetConfig:output_type -> proto.ConfigResponse
	5, // 7: proto.MasterControl.GetCommand:output_type -> proto.Command
	1, // 8: proto.MasterControl.ManageContainer:output_type -> proto.Ack
	1, // 9: proto.MasterControl.ReportCommandResult:output_type -> proto.Ack
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_master_proto_init() }
func file_proto_master_proto_init() {
	if File_proto_master_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_master_proto_rawDesc), len(file_proto_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_master_proto_goTypes,
		DependencyIndexes: file_proto_master_proto_depIdxs,
		MessageInfos:      file_proto_master_proto_msgTypes,
	}.Build()
	File_proto_master_proto = out.File
	file_proto_master_proto_goTypes = nil
	file_proto_master_proto_depIdxs = nil
}
